import Head from "next/head";
import Link from "next/link";
import Button from '@/components/common/Button'
import Homes from '@/components/Home/index'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Homes/>
      </main>
    </>
  );
}
